### ISSUE TITLE
get error on run this command " npm create hono@latest --myapp "

### ISSUE THREAD

**Issue by virenjeet12** [honojs/hono#3704] opened 2024-11-25 17:07 UTC
### What version of Hono are you using?

hono version 0.14.2

### What runtime/platform is your app running on? (with version if possible)

npm

### What steps can reproduce the bug?

npm create hono@latest --honoapp

> npx
> create-hono

create-hono version 0.14.2
? Target directory honoapp
? Which template do you want to use? cloudflare-workers
? Do you want to install project dependencies? no
⠋ Cloning the templateC:\Users\HP\AppData\Local\npm-cache\_npx\6bbb1d6f54609fb5\node_modules\create-hono\bin:31239
    throw new Error(
          ^

Error: Error running hook for cloudflare-workers: ENOTDIR: not a directory, mkdir 'C:\Users\HP\.cache'
    at Command2.main (C:\Users\HP\AppData\Local\npm-cache\_npx\6bbb1d6f54609fb5\node_modules\create-hono\bin:31239:11)

Node.js v20.18.0
npm error code 1
npm error path D:\cohort 2\Hono library
npm error command failed
npm error command C:\windows\system32\cmd.exe /d /s /c create-hono
npm error A complete log of this run can be found in: C:\Users\HP\AppData\Local\npm-cache\_logs\2024-11-25T16_56_23_398Z-debug-0.log

**Comment by MathurAditya724** [comment] 2024-11-30 12:18
Why are you passing `--honoapp` like this? You can pass `--help` to look at the help menu

**Comment by thenetaji** [comment] 2024-12-14 08:36
why you are using `--myapp` like this instead you should `npm create hono@latest my-app`.
The CLI tool doesn't recognize --honoapp as a valid argument. Instead, it expects positional arguments (like my-app).

**Comment by yusukebe** [comment] 2024-12-23 05:17
I think this is not a bug. I'll close this. Thanks.

**Closed by yusukebe** 2024-12-23 05:17 UTC
Labels: triage
