### ISSUE TITLE
env method doesn't work on Cloudflare Pages

### ISSUE THREAD

**Issue by imadoki** [honojs/hono#3158] opened 2024-07-18 15:09 UTC
### What version of Hono are you using?

4.5.0

### What runtime/platform is your app running on?

Cloudflare Pages

### What steps can reproduce the bug?

```.tsx
// src/index.tsx
import { Hono } from "hono";
import { env, getRuntimeKey } from "hono/adapter";
import { renderer } from "./renderer";

const app = new Hono();
app.use(renderer);

type Env = {
  MESSAGE: string;
};

app.get("/", (c) => {
  const { MESSAGE } = env<Env>(c);
  console.log(`MESSAGE: ${MESSAGE}`);
  console.log(`debug MESSAGE: ${c.env.MESSAGE}`);
  console.log(getRuntimeKey());
  return c.json({ message: MESSAGE });
});
```

`vite.config.ts`
```.ts
// vite.config.ts
import build from "@hono/vite-cloudflare-pages";
import devServer from "@hono/vite-dev-server";
import adapter from "@hono/vite-dev-server/cloudflare";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    build(),
    devServer({
      adapter,
      entry: "src/index.tsx",
    }),
  ],
});
```

### What is the expected behavior?

Messages set by `wrangler pages secret put MESSAGE` are displayed.

### What do you see instead?

MESSAGES is undefined

### Additional information

The log returns the following output.

```
  (log) MESSAGE: undefined
  (log) debug MESSAGE: foo
  (log) other
```

**Comment by yusukebe** [comment] 2024-07-18 22:40
Hi @imadoki 

This may be a `@hono/vite-dev-server` matter instead of  `hono`'s. I think this issue was fixed in the last version of it, `@hono/vite-dev-server@0.13.1`. Have you tried it?

**Comment by imadoki** [comment] 2024-07-19 01:07
Thanks for the reply.

I use `@hono/vite-dev-server@0.13.1`.

**Comment by yusukebe** [comment] 2024-07-19 09:19
@imadoki 

The problem is that the value returned from `getRuntimeKey()` is `other` instead of `workerd`. I can't reproduce it in my env; it logs `workerd` correctly. Could you provide a minimal project to reproduce it?

**Comment by imadoki** [comment] 2024-07-20 15:44
I created a minimal project [here](https://github.com/imadoki/env-method-sample).

I think I can reproduce the error with the following steps:

1. clone this repository
2.  `pnpm install` and `pnpm run deploy` (create Cloudflare Pages Project)
3.  `pnpm wrangler pages secret put MESSAGE`
4.  `pnpm run deploy` 

This problem is happening when deploying on Cloudflare Pages, not in the local development environment.

**Comment by yusukebe** [comment] 2024-07-21 12:50
@imadoki 

Thank you very much! This might be fixed by #3171. We'll release a new version that includes that fix later.

**Comment by yusukebe** [comment] 2024-07-21 13:20
Hi @imadoki 

Your issue will be fixed with #3171, but if you set the `compatibility_date` property, it will be fixed without updating the `hono`.

```toml
compatibility_date = "2024-07-20"
```

Can you try it? If it is solved, change #3171 may not be needed.

**Comment by imadoki** [comment] 2024-07-21 14:13
I can confirm that using `compatibility_date` will work around the problem!

Thanks all for the lighting fast response!

**Comment by yusukebe** [comment] 2024-07-22 02:35
@imadoki 

Thank you for confirming it. I'll close this issue.

**Closed by yusukebe** 2024-07-22 02:35 UTC
Labels: triage
