### ISSUE TITLE
Cannot find name 'RequestInfo'. Did you mean 'RequestInit'

### ISSUE THREAD

**Issue by tokenhousetopdev** [honojs/hono#643] opened 2022-11-01 18:27 UTC
Any idea why I am getting this error when running tsc:

```
node_modules/hono/dist/hono.d.ts:47:22 - error TS2552: Cannot find name 'RequestInfo'. Did you mean 'RequestInit'?

47     request: (input: RequestInfo, requestInit?: RequestInit) => Promise<Response>;
```

Config:

```
{
  "compilerOptions": {
    "allowJs": true,
    "target": "esnext",
    "lib": ["esnext"],
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "inlineSourceMap": true,
    "module": "esnext",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strict": true,
    "noImplicitAny": true,
    "noEmit": true,
    "types": [
      "@cloudflare/workers-types"
    ]
  },
  "ts-node": {
    "transpileOnly": true
  },
  "include": ["./src/**/*"]
}

```

**Comment by yusukebe** [comment] 2022-11-02 10:44
Hi @tokenhousetopdev !

This error is caused by type mismatch with `@cloudflare/workers-types`. This PR #645 will fix it and the new version will be released later.

Thank you for creating the issue!

**Closed** 2022-11-03 06:39 UTC
