### ISSUE TITLE
`content-type` not being respected in 2.1.4

### ISSUE THREAD

**Issue by mashaal** [honojs/hono#510] opened 2022-09-09 12:25 UTC
Setting `context.header("Content-Type", "text/css");` still returns `"text/plain"` content-type headers.

Seems to only effect `2.1.4`

I can verify `2.1.2` and `2.1.3` work as intended.

**Comment by yusukebe** [comment] 2022-09-09 12:57
Hi @mashaal !

Thank you for creating the issue. The internal implementation has been changed, indeed.
Could you write down your code or short snippets to reproduce it?

**Comment by that-ambuj** [comment] 2022-09-27 07:03
I experience the same, You shoud try using `c.res.headers.set('Content-Type', 'text/css')` instead.

**Comment by ThatOneBro** [comment] 2022-09-30 15:00
Hi @yusukebe,
I noticed that @that-ambuj found in this node-server repo issue https://github.com/honojs/node-server/issues/3#issuecomment-1259060389 that the .header() was not working. Should this API still be working? If so I can try to correct this issue.

**Comment by yusukebe** [comment] 2022-09-30 15:06
In a general use case it is working correctly. First, we have to reproduce the condition that does not work.

**Comment by that-ambuj** [comment] 2022-09-30 15:13
I think the condition is when you create and use a custom middleware function,which returns a closure of (c, next): Handler function type. Somehow the global c.headers method gets disconnected in custom middlewares but it works perfectly fine in app.use clause.

**Comment by ThatOneBro** [comment] 2022-09-30 15:18
@that-ambuj Wow that's great insight into the problem. I will attempt to see if I can create a minimal example and test case for this.

**Comment by that-ambuj** [comment] 2022-09-30 15:26
That kind of narrows down the problem
```ts
// This works
c.res.headers.set('content-type', 'text/css')
// But this does not
c.headers('content-type', 'text/css')
```

I think you should look into something that is overriding the content-type header.

**Comment by yusukebe** [comment] 2022-09-30 15:29
I believe the Content-Type issue is due to this change. The default Response was specified as `text/plain` because of this change.

https://github.com/honojs/hono/commit/24a28942de1cd4ae8e2c8794830950b35de712bd#diff-0cd594dddd6a9f2e3e26afebbb92716434437d7001c2416252aa7531e7f2b8d4R95

**Comment by yusukebe** [comment] 2022-09-30 15:36
Hmm. It works correctly.

![SS](https://user-images.githubusercontent.com/10682/193305939-38924db0-139c-46b5-bdef-27626d7d4436.png)

![SS](https://user-images.githubusercontent.com/10682/193305981-da8893f3-e2ac-4091-b5d6-561938c7b46a.png)

**Comment by yusukebe** [comment] 2022-09-30 15:42
And, this also works fine:

![SS](https://user-images.githubusercontent.com/10682/193307060-b9154c8a-588c-422c-b2c6-634b5881a8e6.png)

**Comment by that-ambuj** [comment] 2022-09-30 15:44
Try that in a custom middleware.

**Comment by yusukebe** [comment] 2022-09-30 15:47
Like this?:

![SS](https://user-images.githubusercontent.com/10682/193308081-0359a394-54d3-4b89-ae65-79d542e22402.png)

**Comment by that-ambuj** [comment] 2022-09-30 15:55
No, like this :
```ts
// some-middlware.ts
export function middleware() {
    return (c, next) => {
         c.headers(k, v)
    }
}
```
import this in index.ts and use
```ts
app.use('*', middleware())
```

**Comment by that-ambuj** [comment] 2022-09-30 15:57
Also, when I used await next() to set content type in serve static middle, it worked but could not set or send response body, because it was already sent.

**Comment by yusukebe** [comment] 2022-09-30 16:00
Your writing is wrong. The correct version is as follows.

```
const app = new Hono()

const middleware = (): MiddlewareHandler => {
  return async (c, next) => {
    await next()
    c.header('content-type', 'text/css')
  }
}
app.use('*', middleware())
app.use('/', (c) => c.body('h1 { color: #000 }'))
```

**Comment by that-ambuj** [comment] 2022-09-30 16:14
Try setting a body in the middleware after setting headers. I'll reproduce the bug when I'm on my laptop. Although my serve static middleware might be written wrong but that was taken from bun's serve static implementation.

**Comment by yusukebe** [comment] 2022-09-30 17:00
Hmm, it works:

![SS](https://user-images.githubusercontent.com/10682/193320091-d0489b3f-0c8e-4ea6-9957-0d80367fb1ba.png)

Please show me your code and tell me if your environment is Cloudflare Workers, Deno, Bun or Node.js?

**Comment by that-ambuj** [comment] 2022-09-30 17:11
I think, I figured it out. It is not reproducible after around 2.1.4. I checked my lock file before merging from upstream to my fork, I was on version v2.1.4. but in now in my local environment after using v2.2, `c.header()` works perfectly fine.

**Comment by yusukebe** [comment] 2022-09-30 17:27
I found one of the causes: the Serve Static implementation in Bun and Node.js was wrong. Calling `c.res` would initialize the Response in the Context.

https://github.com/honojs/node-server/blob/433695a0a5a74992cf177c3b2dfa8a39f0d66211/src/serve-static.ts#L16

It's not expected behavior. So I made sure not to do `c.res` for Cloudflare Workers, but Bun's code kept it.

I have already fixed it with the following PR:

https://github.com/honojs/node-server/pull/6
https://github.com/honojs/hono/pull/572

I apologize for the confusion.

**Comment by that-ambuj** [comment] 2022-09-30 17:34
I'm sorry for making assumptions about your code. I should carefully read the code I am copying from.

**Comment by ThatOneBro** [comment] 2022-09-30 18:13
Does that mean that this issue may actually have actually been an issue with the Bun implementation in @mashaal 's case? If so, does that mean that it's probably been fixed with this update?

**Comment by that-ambuj** [comment] 2022-10-01 03:06
I think that is the case. No one noticed because there isn't much usage bun js with hono. As @yusukebe mentioned, it was a fix he forgot to do on bun and deno serve static middleware.

**Comment by yusukebe** [comment] 2022-10-01 04:00
> Does that mean that this issue may actually have actually been an issue with the Bun implementation in @mashaal 's case?

I don't know. The above fix resolved the Serve Static Middleware issue for Bun and Node.js, and it is possible that this Issue has not yet been resolved. However, there is nothing wrong with the spec now and all tests have passed.

Therefore, I will close this Issue at this time. If there will be any problems, reopen it or create a new Issue.

**Closed by yusukebe** 2022-10-01 04:00 UTC
