### ISSUE TITLE
Context is not finalized when using Path Parameter with async

### ISSUE THREAD

**Issue by LebCit** [honojs/hono#1236] opened 2023-07-14 20:04 UTC
Hello,
First of all congratulations on this delightful web framework, clean, easy, straightforward and most important without dependencies.
I'm confronting an issue and hope that you can help me solve it.
I have a route file `tagsRoute.js` in a `routes` folder, the `routes` folder is at the root of the Node.js application.
When I try the following code in `tagsRoute.js`

```js
...
import { Hono } from "hono"
import { Eta } from "eta"

const tags = new Hono()
const eta = new Eta({ views: join(process.cwd(), "views") })

export const tagsRoute = tags
	.get("/", async (c) => {
		const res = eta.render("layouts/base.html", {
			...
			data: data,
			tags: await tags(),
			...
		})
		return c.html(res)
	})
	.get("/:tag", async (c) => {
		const tag = c.req.param("tag")
		// List of posts matching the `:tag` request parameter
		const postsByTag = postsByTagList(tag)
		
		const res = eta.render("layouts/base.html", {
			...
			data: data,
			posts: await postsByTag,
			...
		})
		return c.html(res)
	})
```

Then in the application entry file `index.js` I have

```js
...
const app = new Hono()
app.use("/static/*", serveStatic({ root: "./" }))
...
import { tagsRoute } from "./routes/tagsRoute.js"
...
app.route("/tags", tagsRoute)
```

The `/tags` route is working as expected but the `/tags/:tag` route is returning :
**Error: Context is not finalized. You may forget returning Response object or `await next()`**

I've tried to modify the problematic route with `.get("/:tag", async (c, next)` and adding `await next()` before `return c.html(res)` but this does not solve the issue.
I've also tried to move it as a standalone route in the application entry file `index.js` but the problem persists.

Thanks a lot in advance for your time and help.

SYA,
LebCit

**Comment by yusukebe** [comment] 2023-07-15 11:57
Hi @LebCit 

I could not reproduce it with minimal code, this works fine:

```ts
import { Hono } from 'hono'

const tags = new Hono()

const tagsRoute = tags
  .get('/', async (c) => {
    return c.text('Foo')
  })
  .get('/:tag', async (c) => {
    const tag = c.req.param('tag')
    return c.text(tag)
  })

const app = new Hono()

app.route('/tags', tagsRoute)

export default app
```

Can you check it?

**Comment by LebCit** [comment] 2023-07-16 12:43
Hello @yusukebe 

Thank you very much for your response.
I've finally managed to debug the problem, it was a grouping order issue.
A route named `markdownRoute` before the `tagsRoute` have 2 path parameters that where preceding the `:tag` parameter in the `tagsRoute`.
Putting `markdownRoute` after `tagsRoute` solved the issue.
Thank you very much for your time and help.

**Comment by yusukebe** [comment] 2023-07-20 08:57
Great! I'll close this issue.

**Closed by yusukebe** 2023-07-20 08:57 UTC
