### ISSUE TITLE
Cors Middleware error: Can't modify immutable headers.

### ISSUE THREAD

**Issue by anarkrypto** [honojs/hono#1572] opened 2023-10-13 07:20 UTC
### What version of Hono are you using?

3.2.7

### What runtime/platform is your app running on?

Clodflare Workers

### What steps can reproduce the bug?

```js
app.use('*', cors({ origin: '*' }))
```

### What is the expected behavior?

Modify the response headers

### What do you see instead?

Server Internal Error - Status Code 500

Log:
`Trace: TypeError: Can't modify immutable headers.`

### Additional information

response headers cannot be modified

https://github.com/honojs/hono/blob/main/src/middleware/cors/index.ts#L36C18-L36C18

**Comment by yusukebe** [comment] 2023-10-13 08:40
Hi @anarkrypto,

I can't reproduce the bug with only that information. Could you provide a minimal project or snippet to reproduce it?

**Comment by edXmO** [comment] 2023-10-24 08:25
Seems related to #1606.

**Comment by rvause** [comment] 2023-11-07 14:21
I ran into this issue where I was proxying requests with a catch all route to a DurableObject; something like:

```typescript
app.use("*", cors());
app.all("*", async (ctx) => {
  const id = ctx.env.MYOBJECT.idFromName("myobject1");
  const obj = ctx.env.MYOBJECT.get(id);
  return await obj.fetch(ctx.req.raw);
});
```

In the DurableObject I was also routing with another instance of `Hono`. Moving the `app.use("*", cors())` to the instance used by the DurableObject seemed to correct this error for me.

**Comment by nicksrandall** [comment] 2024-01-10 16:39
I'm also seeing this issue when directly returning a response from a `fetch` call in the worker. The CORS middleware must be trying to modify headers of the response of the fetch which are immutable.

**Comment by yusukebe** [comment] 2024-01-10 20:22
@nicksrandall 

This is a Web API limitation. Please create a new Response object and return it as follows.

```ts
app.get('/', async (_c) => {
  const response = await fetch('https://example.com')
  const newResponse = new Response(response.body, response)
  return newResponse
})
```

**Comment by flexchar** [comment] 2024-01-14 08:55
Hi @yusukebe, would you agree that in this context the _Proxy_ example is wrong? Because using exactly same thing I receive same `Can't modify immutable headers.`

Excerpt from URL: https://hono.dev/guides/examples#proxy

```ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/posts/:filename{.+.png$}', (c) => {
  const referer = c.req.header('Referer')
  if (referer && !/^https:\/\/example.com/.test(referer)) {
    return c.text('Forbidden', 403)
  }
  return fetch(c.req.url)
})

app.get('*', (c) => {
  return fetch(c.req.url)
})

export default app
```

**Comment by yusukebe** [comment] 2024-01-14 10:25
If you just return the Response retrieved by `fetch` to the user as is, there is no error. For example, Cloudflare has [an example](https://developers.cloudflare.com/workers/examples/fetch-html/).

```ts
export default <ExportedHandler>{
  async fetch(request) {
    /**
     * Replace `remote` with the host you wish to send requests to
     */
    const remote = "https://example.com";

    return await fetch(remote, request);
  },
};
```

However, if you modify the header of the Response, you will get an error, so you need to clone it.

**Comment by flexchar** [comment] 2024-01-14 10:57
Alright, thanks to your response and this thread it has finally ticked that it's the middlewares (incl. cors) that I'm using that causes the error. Perhaps we should add a comment so for future tinkerers like me it'd be helpful :)

**Comment by yusukebe** [comment] 2024-01-14 14:59
@flexchar Great!

cc: @sor4chi If possible, please consider documenting this matter!

**Comment by sor4chi** [comment] 2024-01-15 02:35
Hi, @yusukebe 
Let me see if I'm interpreting this correctly.
In summary, "If you use a middleware that rewrites headers like cors, you need to register a handler for proxy before that middleware is registered, or generate a new response object from the proxied response and return it"?

**Comment by yusukebe** [comment] 2024-01-15 02:39
@sor4chi 

This is about the following. That is, the Response retrieved by `fetch` can be returned, but if you modify the headers, you need to clone.

https://github.com/honojs/hono/issues/1572#issuecomment-1890910579

**Comment by sor4chi** [comment] 2024-01-15 02:41
@yusukebe 
Understood. I will write this annotation in the example document part of the proxy for now.

**Comment by flexchar** [comment] 2024-01-15 08:01
Thank you!!

**Comment by yusukebe** [comment] 2024-01-30 15:10
Closing.

**Closed by yusukebe** 2024-01-30 15:10 UTC
Labels: bug
