### ISSUE TITLE
CORS error issues when passing `Content-Type: application/json` from the client

### ISSUE THREAD

**Issue by jferrettiboke** [honojs/hono#1872] opened 2023-12-29 17:57 UTC
### What version of Hono are you using?

3.11.11

### What runtime/platform is your app running on?

Vercel

### What steps can reproduce the bug?

```ts
// app/api/[[...route]]/route.ts

import { Hono } from "hono";
import { cors } from "hono/cors";
import { handle } from "hono/vercel";

export const runtime = "edge";

const app = new Hono().basePath("/api");

app.use("*", cors());

app.post("/test", async (c) => {
  const body = await c.req.json();
  return c.json({ ok: true, body });
});

export const POST = handle(app);
```

```ts
// Client

const res = await fetch("http://localhost:3001/api/test", {
  method: "POST",
  headers: { "Content-Type": "application/json", },
  body: JSON.stringify({ hello: "world" }),
});

// ❌ Error: CORS error
```

```ts
// Client

const res = await fetch("http://localhost:3001/api/test", {
  method: "POST",
  body: JSON.stringify({ hello: "world" }),
});

// ✅ It works
```

---

However, when using `zValidator` from `@hono/zod-validator`, I experience this:

```ts
import { zValidator } from "@hono/zod-validator";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { handle } from "hono/vercel";
import { z } from "zod";

export const runtime = "edge";

const app = new Hono().basePath("/api");

app.use("*", cors());

const schema = z.object({
  hello: z.string(),
});

app.post("/test", zValidator("json", schema), async (c) => {
  const body = await c.req.valid("json");
  return c.json({ ok: true, body });
});

export const POST = handle(app);

```

```ts
// Client

const res = await fetch("http://localhost:3001/api/test", {
  method: "POST",
  body: JSON.stringify({ hello: "world" }),
});

// ❌ Error: 400 Bad Request
// { success: false, message: "Invalid HTTP header: Content-Type=text/plain;charset=UTF-8" }
```

```ts
// Client

const res = await fetch("http://localhost:3001/api/test", {
  method: "POST",
  headers: { "Content-Type": "application/json", },
  body: JSON.stringify({ hello: "world" }),
});

// ❌ Error: CORS error
```

### What is the expected behavior?

I should get CORS to work when passing `Content-Type: application/json` from the client.

### Additional information

Dependencies:

```
"@hono/zod-validator": "^0.1.11",
"hono": "^3.11.11",
"next": "14.0.4",
"react": "^18",
"react-dom": "^18",
"zod": "^3.22.4",
```

**Comment by yusukebe** [comment] 2023-12-31 03:00
Hi @jferrettiboke 

I can't reproduce it. Please share the minimal project to reproduce it.

**Comment by frankieali** [comment] 2024-01-24 17:25
I just started a new Hono project with Bun and I'm encountering this issue as well. Version 3.12.6. My first time using Hono and can not for the life of me figure out what I'm doing wrong with my barebones setup that is pretty much like the OP's example.

**Comment by frankieali** [comment] 2024-01-24 18:00
I went back and installed older version of hono to trace down when it did last work. I worked my way up from hono@3.10 but I never encountered the cors issue again. Even all the way back up to the latest version at 3.12.6? Perhaps there's a missing dependency in the latest package.

**Comment by yusukebe** [comment] 2024-01-25 20:59
Hi @frankieali 

This works fine on Bun.

```tsx
import { zValidator } from '@hono/zod-validator'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { raw } from 'hono/html'
import { z } from 'zod'

const schema = z.object({
  hello: z.string(),
})

const app = new Hono().basePath('/api')
app.use('/api/*', cors())

app.post('/test', zValidator('json', schema), (c) => {
  const body = c.req.valid('json')
  return c.json({ ok: true, body })
})

app.get('/', (c) => {
  return c.html(
    <html>
      <body>
        <script>
          {raw(`
        (async () => {
            const res = await fetch("http://localhost:3000/api/test", {
            method: "POST",
            headers: { "Content-Type": "application/json", },
            body: JSON.stringify({ hello: "world" }),
          })
          console.log(await res.json())
        })();`)}
        </script>
      </body>
    </html>
  )
})

export default app
```

**Comment by yusukebe** [comment] 2024-03-25 17:57
I can't reproduce it on Bun. And it's not related to Vercel's matter. We can close it now

**Closed by yusukebe** 2024-03-25 17:57 UTC
Labels: bug
