### ISSUE TITLE
Pusher and honojs Crypto error Nextjs

### ISSUE THREAD

**Issue by AlejandroSanchez90** [honojs/hono#3283] opened 2024-08-17 01:54 UTC
### What version of Hono are you using?

4.4.7

### What runtime/platform is your app running on?

bun

### What steps can reproduce the bug?

build a post request, then try to trigger a Pusher event from it

### What is the expected behavior?

receive the pushed event in my frontend

### What do you see instead?

i get this error 
```
./node_modules/pusher/lib/pusher.js:1:1
Module not found: Can't resolve 'crypto'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./lib/pusher.ts
./app/api/[[...route]]/ro.ts
./app/api/[[...route]]/route.ts
./node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?absolutePagePath=%2Fhome%2Falejandro%2F.dev%2Ftoyota-ro%2Fapp%2Fapi%2F%5B%5B...route%5D%5D%2Froute.ts&page=%2Fapi%2F%5B%5B...route%5D%5D%2Froute&appDirLoader=bmV4dC1hcHAtbG9hZGVyP25hbWU9YXBwJTJGYXBpJTJGJTVCJTVCLi4ucm91dGUlNUQlNUQlMkZyb3V0ZSZwYWdlPSUyRmFwaSUyRiU1QiU1Qi4uLnJvdXRlJTVEJTVEJTJGcm91dGUmYXBwUGF0aHM9JnBhZ2VQYXRoPXByaXZhdGUtbmV4dC1hcHAtZGlyJTJGYXBpJTJGJTVCJTVCLi4ucm91dGUlNUQlNUQlMkZyb3V0ZS50cyZhcHBEaXI9JTJGaG9tZSUyRmFsZWphbmRybyUyRi5kZXYlMkZ0b3lvdGEtcm8lMkZhcHAmcGFnZUV4dGVuc2lvbnM9dHN4JnBhZ2VFeHRlbnNpb25zPXRzJnBhZ2VFeHRlbnNpb25zPWpzeCZwYWdlRXh0ZW5zaW9ucz1qcyZyb290RGlyPSUyRmhvbWUlMkZhbGVqYW5kcm8lMkYuZGV2JTJGdG95b3RhLXJvJmlzRGV2PXRydWUmdHNjb25maWdQYXRoPXRzY29uZmlnLmpzb24mYmFzZVBhdGg9JmFzc2V0UHJlZml4PSZuZXh0Q29uZmlnT3V0cHV0PSZwcmVmZXJyZWRSZWdpb249Jm1pZGRsZXdhcmVDb25maWc9ZTMwJTNEIQ%3D%3D&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!
```

### Additional information

it dosent happen on a regular nextjs route

**Comment by yusukebe** [comment] 2024-08-20 00:34
@AlejandroSanchez90 

This seems to be not a Hono matter. If you still think this is a bug on Hono's side, please provide a minimal project to reproduce it.

**Comment by yusukebe** [comment] 2024-08-31 02:31
I'll close this issue. If you have any problem on Hono-side, please reopen it.

**Closed by yusukebe** 2024-08-31 02:31 UTC
Labels: triage
