### ISSUE TITLE
Support for multiple file uploads under the same key

### ISSUE THREAD

**Issue by ivyrze** [honojs/hono#1527] opened 2023-09-29 23:21 UTC
Currently it's not possible to handle multiple files uploaded at once (`<input type="file" name="...[]" multiple />`) while using validators or `parseBody`. Looks like this is because any arrays that are uploaded get stringified:

https://github.com/honojs/hono/blob/dddd4978d81cbc526622f14a74d8ca41dc1126b9/src/utils/body.ts#L20-L22

Workaround is available by using `await c.req.formData()` and manually building the array.

**Comment by yusukebe** [comment] 2023-09-30 12:31
Duplicate of #1018

**Closed** 2023-09-30 12:34 UTC
Labels: v4

**Comment by muhaimincs** [comment] 2024-06-09 19:52
how's the workaround for this?

**Comment by ivyrze** [comment] 2024-06-10 01:25
I did something like this inside of the handler:

```js
const form = await c.req.formData();
const files = form.getAll('filesKey');
```

The `files` will be `[File](https://developer.mozilla.org/en-US/docs/Web/API/File)[]`, so you might have to map over it if you need a different type.

If anyone knows a better way I’d be curious to know. If not hope they fix this.
