### ISSUE TITLE
c.json() not setting status code correctly 

### ISSUE THREAD

**Issue by abdurahmanshiine** [honojs/hono#3155] opened 2024-07-18 10:12 UTC
### What version of Hono are you using?

3.9.1

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I have the following code that's catching errors:
```ts
app.onError(async (err, c): Promise<Response> => {
      if (err instanceof BaseError) return c.json({ message: err.message }, err.statusCode)
      else return c.json({
          message: "Internal Server Error",
      }, 500)
})
```

This is my custom error definition:
```ts
export abstract class BaseError extends Error {
    abstract statusCode: number;

    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, BaseError.prototype);
  }

    abstract serializeErrors(): { statusCode: number, message: string };
}

export default class ValidationError extends BaseError {
    statusCode: number = 400;

    constructor(public message: string) {
        super("Invalid request parameters");
        Object.setPrototypeOf(this, ValidationError.prototype);
    }

    serializeErrors() {
        return { statusCode: this.statusCode, message: this.message };
    }
}
```

I have a middleware throwing this error `ValidationError`, and I want to handle it with the `app.onError` code above

### What is the expected behavior?

That when the error is thrown; the response comes with status code 400

### What do you see instead?

The status code is always 200 no matter what I do. I tried using `c.status()` before calling `c.json()` but that changed nothing as well.

**Comment by yusukebe** [comment] 2024-07-18 10:24
Hi @abdurahmanshiine 

I can't reproduce it. It throws a `400` correctly in my project. Can you share a minimal project to reproduce it?

**Comment by abdurahmanshiine** [comment] 2024-07-18 10:43
I uploaded a workable minimal setup [here](https://github.com/abdurahmanshiine/hono-boilerplate/tree/main)

**Comment by yusukebe** [comment] 2024-07-18 12:12
@abdurahmanshiine 

Thank you. But to debug easily, please provide only the part where the error occurs instead of the entire project.

**Comment by abdurahmanshiine** [comment] 2024-07-22 09:25
Hey @yusukebe,

Apologies for the late reply, but I think I figured it out. I used this library called [bun-compression](https://github.com/sunneydev/bun-compression) which does the compression for Bun since Bun doesn't support that yet. It turns out this package converts all status codes to 200 no matter what, I only figured it out after doing this:

```ts
import { Hono } from 'hono'
import { compress } from 'bun-compression'

const app = new Hono()

app.use("*", compress())

app.get('/', (c) => {
  return c.text('Hello Hono!', 201)
})

export default app
```

Unfortunately, new issues can't be opened on their repository for some reason, so I'll just have to drop the compression I guess (I'm open to any suggestions regarding that).

Thanks for the help.

**Comment by yusukebe** [comment] 2024-07-23 11:09
Hi @abdurahmanshiine 

Thank you! Fully understood. With a quick look, I think these lines should be fixed since the status code in the context is not applied:

https://github.com/sunneydev/bun-compression/blob/9f8f1a5eae7f6a38fd8e4738d283fcefd329913c/src/index.ts#L61-L63

**Comment by abdurahmanshiine** [comment] 2024-07-25 06:37
That's interesting, I'll see if I can contact the package author and alert him. Meanwhile, on my side, I ended up adding my own Streams like so:

```ts
import zlib from 'node:zlib'

const make = (ctx: any, handle: any) => Object.assign(ctx, {
  writable: new WritableStream({
    write: chunk => handle.write(chunk),
    close: () => handle.end()
  }),
  readable: new ReadableStream({
    type: 'bytes',
    start(ctrl) {
      handle.on('data', (chunk: ArrayBufferView) => ctrl.enqueue(chunk))
      handle.once('end', () => ctrl.close())
    }
  })
})

globalThis.CompressionStream ??= class CompressionStream {
  constructor(format: string) {
    make(this, format === 'deflate' ? zlib.createDeflate() :
      format === 'gzip' ? zlib.createGzip() : zlib.createDeflateRaw())
  }
}

globalThis.DecompressionStream ??= class DecompressionStream {
  constructor(format: string) {
    make(this, format === 'deflate' ? zlib.createInflate() :
      format === 'gzip' ? zlib.createGunzip() :
        zlib.createInflateRaw())
  }
}
```

And it works fine. I'm leaving this here in case anyone is looking for a quick temporary solution

**Comment by yusukebe** [comment] 2024-07-26 01:06
@abdurahmanshiine 

Nice. I'll close this issue since it's not Hono's issue. Thanks!

**Closed by yusukebe** 2024-07-26 01:06 UTC
Labels: triage

**Comment by ThinLiquid** [comment] 2025-01-17 12:16
> Hey [@yusukebe](https://github.com/yusukebe),
> 
> Apologies for the late reply, but I think I figured it out. I used this library called [bun-compression](https://github.com/sunneydev/bun-compression) which does the compression for Bun since Bun doesn't support that yet. It turns out this package converts all status codes to 200 no matter what, I only figured it out after doing this:
> 
> import { Hono } from 'hono'
> import { compress } from 'bun-compression'
> 
> const app = new Hono()
> 
> app.use("*", compress())
> 
> app.get('/', (c) => {
>   return c.text('Hello Hono!', 201)
> })
> 
> export default app
> Unfortunately, new issues can't be opened on their repository for some reason, so I'll just have to drop the compression I guess (I'm open to any suggestions regarding that).
> 
> Thanks for the help.

just to let you know, i've put out a PR towards the repo implementing a fix.

**Comment by EdamAme-x** [comment] 2025-01-17 12:34
Great work!
