### ISSUE TITLE
(@hono/node-server) I can't close web server

### ISSUE THREAD

**Issue by ringo360** [honojs/hono#3104] opened 2024-07-06 10:17 UTC
### What version of Hono are you using?

4.4.11

### What runtime/platform is your app running on?

Node.js

### What steps can reproduce the bug?

1. Write code
```ts
// utils/Scheduler.ts
import consola from 'consola';
import color from 'picocolors';
import { setTimeout } from 'timers/promises';

const closeListeners: any = [];

export async function shutdown() {
	consola.start(color.italic('Shutting down...'));
	try {
		await Promise.race([
			Promise.all(closeListeners.map((closeListener: any) => closeListener())),
			setTimeout(5000),
		]);
	} catch (e) {
		console.error(e);
	}
	consola.success(color.italic('Goodbye!'));
	process.exit(0);
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

/**
 * @param {() => (void | Promise<void>)} task
 */
export function onShutdown(task: any) {
	closeListeners.push(task);
}
```

```ts
// websv.ts
import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import consola from 'consola';
import color from 'picocolors';
import { config } from './utils/CLoader';
import { onShutdown } from './utils/Scheduler';

const app = new Hono();

app.get('/', (c) => c.text('Hello Node.js!'));

const websv = serve({
	fetch: app.fetch,
	port: config.web.port,
});

//prettier-ignore
consola.info(color.green(`[WebSV] Web Server is ready on port ${color.cyan(config.web.port)}`));

onShutdown(() => {
	consola.info(color.cyan('[WebSV] Called shutdown event'));
	websv.close();
	consola.info(color.red('[WebSV] Closed web server'));
});
```

2. run
3. Press ctrl+c or kill task
4. Program will exit with code 1

### What is the expected behavior?

The program should have terminated with code 0 and a graceful shutdown should have been achieved.

### What do you see instead?

You can confirm that the code is not terminating as expected:
![Terminal(VSCode)](https://github.com/honojs/hono/assets/105296365/aa78c2bf-f35c-4a51-8e70-e296de0d9f60)

> When I ran shutdown with the exception of websv.ts, the exit code was 0.

**Comment by yusukebe** [comment] 2024-07-07 07:38
Hi @ringo360 

I've tried your code. Below is the behavior on my machine.

https://github.com/honojs/hono/assets/10682/1c1f938b-d03e-4824-bfca-215cef8f4a0d

I think this is expected behavior. If you still have a problem, could you provide a minimal project to reproduce it?

**Comment by ringo360** [comment] 2024-07-07 16:42
Ok, I'll prepare a minimum project.

**Comment by EdamAme-x** [comment] 2024-07-07 23:55
I think this is not a problem of hono
![image](https://github.com/honojs/hono/assets/121654029/627bb226-b0e1-49b7-86cd-b6e55f194b50)

Sample repo
https://github.com/EdamAme-x/hono-issue-3104

**Comment by ringo360** [comment] 2024-07-08 01:59
I created repo
https://github.com/ringo360/hono-i3104/

**Comment by yusukebe** [comment] 2024-07-08 09:25
@ringo360 Thanks!

I've tried it, and it will throw status code `130` since I typed Ctrl+C.

https://github.com/honojs/hono/assets/10682/ac7c9b35-719f-4c9e-bf73-e93352832c75

So, the behavior may change depending on the environment. We have to figure out if it's Hono matter or not. Can you try some cases like it without Hono?

```ts
import consola from 'consola'
import color from 'picocolors'
import { config } from './utils/CLoader'
import { onShutdown } from './utils/Scheduler'
import http from 'http'

const server = http.createServer((_req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' })
  res.end('Hello Node.js!')
})

server.listen(config.web.port, () => {
  consola.info(color.green(`[WebSV] Web Server is ready on port ${color.cyan(config.web.port.toString())}`))
})

onShutdown(() => {
  consola.info(color.cyan('[WebSV] Called shutdown event'))
  server.close(() => {
    consola.info(color.red('[WebSV] Closed web server'))
  })
})
```

**Comment by ringo360** [comment] 2024-07-08 11:41
Sorry, this seems to be a problem in another area.
It threw status code `1` when I typed Ctrl+C.

https://github.com/honojs/hono/assets/105296365/280b2b90-ad9a-456d-ad0a-664be15cfcfa

**Comment by yusukebe** [comment] 2024-07-11 07:44
@ringo360 

So, is not the issue on the Hono side?

**Comment by ringo360** [comment] 2024-07-11 10:28
@yusukebe Probably yes, may I close this issue?

**Comment by yusukebe** [comment] 2024-07-11 14:59
@ringo360 

Okay! I'll close this issue. If you have any problem, feel free to reopen it.

**Closed by yusukebe** 2024-07-11 14:59 UTC
Labels: triage

**Comment by ringo360** [comment] 2024-07-11 22:35
tysm <3
