### ISSUE TITLE
hono/client Typescript Generic error: property '#private' is missing

### ISSUE THREAD

**Issue by redbaron76** [honojs/hono#3233] opened 2024-08-05 14:41 UTC
### What version of Hono are you using?

4.5.3

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

After setting up a simple monorepo app with Hono as backend and React/Vite as frontend, 
I have a simple Hono app that says:

```
import { Hono } from "hono";

const app = new Hono();

const route = app.get("/test", async (c) => {
  return c.json({ success: true });
});

export type TestRoute = typeof route;
```

```
import { type TestRoute } from "@backend/app";
import { hc } from "hono/client";

const client = hc<TestRoute>("/");

export const api = client.api;
```

but in this case TypeScript rises an error in the generic usage.

### What is the expected behavior?

The expected behavior is the exported TestRoute type to be accepted as generic without Typescript error.

### What do you see instead?

Property '#private' is missing in type 'Hono<BlankEnv, { "/test": { $get: { input: {}; output: { success: boolean; }; outputFormat: "json"; status: StatusCode; }; }; }, "/">' but required in type 'Hono<any, any, any>'.

**Comment by msickpaler** [comment] 2024-08-17 08:59
@redbaron76 

It may not be a fundamental solution, but in my experience, if you match the hono versions of the two projects, you will not get that error.

**Comment by yusukebe** [comment] 2024-08-20 00:31
As @msickpaler mentioned, this problem occurs because both projects do not refer to the same `hono` package. This is not a bug. I'll close this issue now. If you still have the problem, provide a minimal project to reproduce the behavior and reopen it.

**Closed by yusukebe** 2024-08-20 00:31 UTC
Labels: triage
