### ISSUE TITLE
Hono corrupts response body when using nextjs handler

### ISSUE THREAD

**Issue by Artrix9095** [honojs/hono#1893] opened 2024-01-03 18:32 UTC
### What version of Hono are you using?

Next.js v14.0.4 Hono v3.11.12 Bun v1.0.20

### What runtime/platform is your app running on?

Bun & Nodejs

### What steps can reproduce the bug?

```bash
bunx create-next-app # install next
```

```bash
bun add hono discord-api-types discord-interactions
```

```ts
// /api/interactions/route.ts

import { APIInteraction, InteractionType, InteractionResponseType as ResponseType } from "discord-api-types/v10"
import { verifyKey } from "discord-interactions"
import { Hono, type Context, type Next } from "hono"
import { handle } from "hono/vercel"



const verifySignature = async (ctx: Context, next: Next) => {
  console.log("Verifying body...")
  // Clone the body
  const body = await ctx.req.raw.clone().arrayBuffer()

  const sig = ctx.req.raw.headers.get("x-signature-ed25519")
  const timestamp = ctx.req.raw.headers.get("x-signature-timestamp")

  if (!sig || !timestamp) return ctx.text("Invalid signature", 401)

  return !verifyKey(body, sig, timestamp, process.env.BOT_PUBLIC_KEY!) ? ctx.text("Invalid signature", 401) : next()
}

const app = new Hono().basePath("/api/interactions")

app.all("/", verifySignature, async (c) => {
    console.log({ "content-type": c.req.header("content-type"), body: await c.req.text() })
  })
)

const handler = handle(app)

export const GET = handler
export const POST = handler
export const PUT = handler
```

### What is the expected behavior?

See discord/discord-api-docs#6596

**Comment by yusukebe** [comment] 2024-01-08 14:25
Hi @Artrix9095 

I can't reproduce it. Please tell us what request you are actually sending to that endpoint, not from the Discord application.

**Comment by yusukebe** [comment] 2024-01-30 15:09
Closing. If you have any problems, please reopen

**Closed by yusukebe** 2024-01-30 15:09 UTC
Labels: bug

**Comment by riderx** [comment] 2024-02-18 05:39
same problem for stribe webhook the signature doesn't match
