### ISSUE TITLE
Path parameter not accessible when using app.onError()

### ISSUE THREAD

**Issue by justinwride** [honojs/hono#1590] opened 2023-10-17 05:48 UTC
### What version of Hono are you using?

3.8.0

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

When using `app.onError()` within a nested route, the path parameters are not accessible.

`c.req.param('assignmentId')` does not work when `app.onError(err, c)` is in the nested route file

index.js
routes/example.js

See this project for example: https://github.com/justinwride/hono-path

### What is the expected behavior?

I expect to access the path parameter for the route **/assignments/:assignmentId?** using `c.req.param('assignmentId')`

### What do you see instead?

Instead, `c.req.param('assignmentId')` is `undefined`

### Additional information

It works if `app.onError()` is put in **index.js**, but not if it is used in **routes/example.js**.

I have been experimenting with Hono and enjoy the simplicity and speed. I'm the CTO of an ed-tech company and hope to use it more in our tech stack.

**Comment by usualoma** [comment] 2023-10-17 21:29
Hi @justinwride 
Thanks for the report. This appears to be a bug caused by #1566 and will be investigated.

**Closed** 2023-10-18 03:28 UTC
Labels: bug

**Comment by yusukebe** [comment] 2023-10-18 03:40
Hi @justinwride!

Thank you for reporting with the kind explanation.

This issue has been fixed by @usualoma's implementation and the release v3.8.1 includes it. Please give it a try!

**Comment by justinwride** [comment] 2023-10-18 18:04
Thanks @yusukebe and @usualoma! 💯 

The fix was very quick and works perfectly. Hono is awesome!
