### ISSUE TITLE
hono/bun getConnInfo() function not working

### ISSUE THREAD

**Issue by hanumanjiblog** [honojs/hono#3351] opened 2024-09-01 02:50 UTC
### What version of Hono are you using?

4.5.4

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

    try {
      console.log(getConnInfo(c));
    } catch (e) {
      console.log(e);
    }
    /*
     9 |     throw new TypeError("server.requestIP is not a function.");
    10 |   }
    11 |   const info = server.requestIP(c.req.raw);
    12 |   return {
    13 |     remote: {
    14 |       address: info.address,
                        ^
    TypeError: null is not an object (evaluating 'info.address')
      at getConnInfo (C:\Users\one\Desktop\Code\node_modules\hono\dist\adapter\bun\conninfo.js:14:16)
      at C:\Users\one\Desktop\Code\2-quiz.ts:110:19
    */

**Comment by yusukebe** [comment] 2024-09-02 02:44
Hi @hanumanjiblog 

I can't reproduce it if you want to have more help. Please provide a minimal project to reproduce it.

**Comment by yusukebe** [comment] 2024-09-29 10:09
Still, I can't reproduce this problem. I'll close this issue. If you will provide a minimal project to reproduce it, feel free to reopen it.

**Closed by yusukebe** 2024-09-29 10:09 UTC
Labels: triage

**Comment by Agamennon** [comment] 2024-10-02 21:58
I am having this problem too, trying to use getConnInfo(c) results in server.requestIP is not a function,  run of the mill hono server with SPA, vite on top  (api proxied) latest versions.

**Comment by maou-shonen** [comment] 2024-10-03 02:31
I encountered the same issue, and I saw that this issue has not been resolved. Then I checked my Bun version (1.1.17). After upgrading to the latest version (1.1.29), the issue was resolved.

**Comment by tripolskypetr** [comment] 2025-01-13 12:34
Why the fuck this is closed. This still reads the env.server which is undefined
