### ISSUE TITLE
Fetch does not send headers, body 

### ISSUE THREAD

**Issue by mykhailovz** [honojs/hono#2842] opened 2024-05-28 12:49 UTC
### What version of Hono are you using?

4.1.5 4.4.0

### What runtime/platform is your app running on?

Node.js v20.13.1 aws lambda

### What steps can reproduce the bug?

code snippet to reproduce and issue:

```typescript
app.post("/http-bin-post", async (c) => {
  console.log("--- hit /http-bin-post");

  const { code, scope, grant_type } = await c.req.parseBody();
  const authorization = c.req.header("authorization");

  const headers = new Headers();
  headers.append("content-type", "application/x-www-form-urlencoded");
  headers.append("authorization", authorization as string);

  const urlencoded = new URLSearchParams();
  urlencoded.append("grant_type", grant_type as string);
  urlencoded.append("scope", scope as string);
  urlencoded.append("code", code as string);

  const response = await fetch("https://httpbin.org/post", {
    method: "POST",
    headers: headers,
    body: urlencoded,
    redirect: "follow",
  });

  const data = await response.json();

  console.log("--- status", response.status);
  console.log("--- statusText", response.statusText);

  return c.json(data);
});
```

### What is the expected behavior?

we expect fetch to correctly pass headers, body, etc.

Expected response from httpbin:
```json
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "code": "code_VALUE",
        "grant_type": "grant_type_VALUE",
        "scope": "scope_VALUE"
    },
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "br, gzip, deflate",
        "Accept-Language": "*",
        "Authorization": "Bearer authorization",
        "Content-Length": "60",
        "Content-Type": "application/x-www-form-urlencoded",
        "Host": "httpbin.org",
        "Sec-Fetch-Mode": "cors",
        "User-Agent": "node",
       "X-Amzn-Trace-Id": "Root=0-00000000-000000000000000000000000"
    },
    "json": null,
    "origin": "11.111.11.111",
    "url": "https://httpbin.org/post"
}
```

### What do you see instead?

Response from httpbin:
```json
{
    "args": {},
    "headers": {
        "Host": "httpbin.org",
        "X-Amzn-Trace-Id": "Root=0-00000000-000000000000000000000000"
    },
    "origin": "1.111.111.111",
    "url": "https://httpbin.org/post"
}
```

### Additional information

We can not reproduce this issue locally it is reproducible only in aws lambda. Interestingly, for the last few months, we have been using the version and everything was working correctly and suddenly a problem appeared. Axios library is working correctly.

**Comment by watany-dev** [comment] 2024-05-29 02:32
As it turns out, we were unable to reproduce it v4.4.0.

The environment is created as follows and called from API Gateway
https://hono.dev/getting-started/aws-lambda

The code is here.

```ts
import { Hono } from 'hono'
import { handle } from 'hono/aws-lambda'

const app = new Hono()
app.get('/', (c) => c.text('Hello Hono!'))

app.post("/http-bin-post", async (c) => {
  console.log("--- hit /http-bin-post");

  const { code, scope, grant_type } = await c.req.parseBody();
  const authorization = c.req.header("authorization");

  const headers = new Headers();
  headers.append("content-type", "application/x-www-form-urlencoded");
  headers.append("authorization", authorization as string);

  const urlencoded = new URLSearchParams();
  urlencoded.append("grant_type", grant_type as string);
  urlencoded.append("scope", scope as string);
  urlencoded.append("code", code as string);

  const response = await fetch("https://httpbin.org/post", {
    method: "POST",
    headers: headers,
    body: urlencoded,
    redirect: "follow",
  });

  const data = await response.json();

  console.log("--- status", response.status);
  console.log("--- statusText", response.statusText);

  return c.json(data);
});

export const handler = handle(app)
```

The result looks like this, and the Header is given as expected
```bash
curl -X POST https://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/prod/http-bin-post
{"args":{},"data":"","files":{},"form":{"code":"undefined","grant_type":"undefined","scope":"undefined"},"headers":{"Accept":"*/*","Accept-Encoding":"br, gzip, deflate","Accept-Language":"*","Authorization":"undefined","Content-Length":"51","Content-Type":"application/x-www-form-urlencoded","Host":"httpbin.org","Sec-Fetch-Mode":"cors","User-Agent":"node","X-Amzn-Trace-Id":"Root=1-6656924c-199c76ce0bd1470d11d66695"},"json":null,"origin":"xx.xx.xx.xx","url":"https://httpbin.org/post"}
```

**Comment by mykhailovz** [comment] 2024-05-29 13:41
Hello @watany-dev thanks for checking this.
You are right `hono` does not cause this issue.
After a closer inspection, I found that it was caused by this particular package `opentelemetry-instrumentation-fetch-node`.
By updating this package from version `1.1.2` to `1.2.0` we managed to solve the problem

**Comment by yusukebe** [comment] 2024-06-02 08:57
> After a closer inspection, I found that it was caused by this particular package `opentelemetry-instrumentation-fetch-node`. By updating this package from version `1.1.2` to `1.2.0` we managed to solve the problem

Good! @mykhailovz Can we close this issue now?

**Comment by mykhailovz** [comment] 2024-06-03 09:30
Hello @yusukebe 
yeah please close this issue.

**Closed** 2024-06-04 12:57 UTC
Labels: bug
