### ISSUE TITLE
Hono does not seem to work correctly with Vue

### ISSUE THREAD

**Issue by buzzy** [honojs/hono#3212] opened 2024-07-29 20:42 UTC
### What version of Hono are you using?

4.5.3

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Pull this repo: https://github.com/buzzy/hono-vue

Look in the file **/src/api/server.ts**
It's a very simple example that uses hono and zod-validator
![image](https://github.com/user-attachments/assets/c1590205-21f1-45f4-bf29-a2a1acdcdb0c)

Look in the file **/src/api/client.ts**
![image](https://github.com/user-attachments/assets/6a8dc0dc-29eb-4521-94e7-3afda357bd21)

As you can see in the picture, all the types get imported correctly.

Now open file **/src/views/HomeView.vue**
This is a Vue component file.
![image](https://github.com/user-attachments/assets/80948f71-c1b3-4809-bb73-74fd34bb5fcd)

Using the exact same imports as in the server.ts, all types are working **except for the input type**. It's blank.

### What is the expected behavior?

That all the types are imported, including the "input" attribute.

### What do you see instead?

When using Hono RPC in a Vue component, the "input" is always blank.

**Comment by EdamAme-x** [comment] 2024-07-30 01:43
Is there any possibility that an extension (.ts, .js) is needed?  
There is a possibility that it is necessary depending on the configuration.

**Comment by yusukebe** [comment] 2024-08-05 13:18
Hi @buzzy 

Add a `strict: true` in your `tsconfig.json`:

```diff
diff --git a/tsconfig.json b/tsconfig.json
index 66b5e57..5c6a83b 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -1,5 +1,8 @@
 {
   "files": [],
+  "compilerOptions": {
+    "strict": true
+  },
   "references": [
     {
       "path": "./tsconfig.node.json"
@@ -8,4 +11,4 @@
       "path": "./tsconfig.app.json"
     }
   ]
-}
+}
```

**Comment by yusukebe** [comment] 2024-08-31 02:45
I'll close this issue. If you need any help related to Hono, please reopen. Anyway, this issue is caused by TypeScript settings.

**Closed by yusukebe** 2024-08-31 02:45 UTC
Labels: not bug
