### ISSUE TITLE
Abort is crashing the server in Bun

### ISSUE THREAD

**Issue by abaudhuin** [honojs/hono#3064] opened 2024-06-30 23:29 UTC
### What version of Hono are you using?

4.4.10

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Following up of #3032 which solved the issue but something else is going on. 

When hooking up OpenAI streaming library with a Hono SSE endpoint, an abort to the client makes the hole server stop.
The logs:
``` SH
> bun run t.js          
aborted
AbortError: The operation was aborted.

Bun v1.1.17 (Linux x64)
```

The code:
``` JS
import { Hono } from "hono";
import { streamSSE } from "hono/streaming";
import { OpenAI } from "openai";
// import { serve } from "@hono/node-server";

const hono = new Hono();

const openai = new OpenAI();

hono.get("t", async (c) => {
  const thread = await openai.beta.threads.create();
  const assistantStream = openai.beta.threads.runs.stream(thread.id, {
    assistant_id: "XXX",
    additional_messages: [
      {
        role: "user",
        content: "Count from 1 to 100 in letters",
      },
    ],
  });
  return streamSSE(c, async (stream) => {
    stream.onAbort(() => {
      assistantStream.controller.abort();
    });
    return new Promise((resolve, reject) => {
      assistantStream
        .on("event", (event) => {
          stream.writeSSE({
            event: "event",
            data: JSON.stringify(event),
          });
        })
        .on("abort", () => {
          console.log("aborted");
          resolve();
        })
        .on("end", resolve)
        .on("error", (err) => {
          console.error(err);
          reject(err);
        });
    });
  });
});

// serve(hono);
export default hono;
```

Again, it works normally with NodeJS.
I'm not sure if it's caused by Bun itself or if Hono is missing a catch or something.

**Comment by yusukebe** [comment] 2024-07-01 08:19
Hi @abaudhuin 

Can you figure out if it is caused by Hono's side or the "OpenAI and Bun" matter?

**Comment by abaudhuin** [comment] 2024-07-01 12:28
HI @yusukebe 

I tried having a look but i can't figure out myself, sorry. 
The only thing I can see is that this error is logged `AbortError: The operation was aborted.` and it's not the case with NodeJS.
I'm guessing it's originated from Bun but I'm not sure if it's a broken behavior from Bun or error handling issue from Hono.

**Comment by Jarred-Sumner** [comment] 2024-07-01 20:47
This could be a bug in Bun, or it could be a missing exception handler where streams are used

**Comment by abaudhuin** [comment] 2024-07-01 22:42
New findings.

I implemented the stream manually without the OpenAI lib:

``` JS
hono.get("t", async (c) => {
  const controller = new AbortController();
  // Dummy stream from example doc
  const r = await fetch("http://localhost:3000/t", {
    signal: controller.signal,
  });
  return streamSSE(c, async (stream) => {
    stream.onAbort(() => {
      controller.abort();
    });
    return new Promise((resolve, reject) => {
      const reader = r.body.getReader();
      const decoder = new TextDecoder();
      const read = async () => {
        try {
          const { done, value } = await reader.read();  // THIS LINE HERE
          if (done) {
            stream.close();
            resolve();
            return;
          }
          stream.writeSSE({
            data: decoder.decode(value),
            event: "time-update",
          });
          read();
        } catch (e) {
          if (e.name === "AbortError") {
            resolve();
            return;
          }
          console.error(e);
          reject(e);
        }
      };
      read();
    });
  });
});
```

This works fine: abortError is properly catched.
However, if I move the `reader.read()` line up 1 line outside of the `try`, it reproduces the global crash of my initial case.

Tbh I'm not really sure what it means in term of source of the issue.
Do you have any insights?

**Comment by flexchar** [comment] 2024-07-18 18:01
I think it makes sense given your most recent example. When exception occurs and there's no one to catch, it makes sense Bun _crashes_. It does because it doesn't know any better. You haven't told it. 

But when you put in `try...catch`, you do tell it what to do and so it works as expected.


This may help you.

When you return a streaming response, Hono has successfully completed its job. However you still have a process running and if it crashes, it won't be caught by Hono `onError` handler. This is something that I had to learn myself twice. It might be the source of your confusion too.

This means that it is your own responsibility to catch any exceptions that occur in the code after Hono has returned response (in this case `streamSSE` one). 

I think the last section here tells the same thing too. https://hono.dev/docs/helpers/streaming#error-handling

Let me know what you think!

**Comment by abaudhuin** [comment] 2024-07-18 21:04
Hello, thanks for your answer.

Sorry my previous message is both a bit wrong and miss leading. 

Here is a repo with a step by step repro: https://github.com/abaudhuin/bun-hono-stream-abort-repro
(You will need an OpenAI key and and assistant ID)

I couldn't reproduce without OpenAI's lib but the behavior is still very suspect.
After a streamed request being aborted the entire process seems to be frozen. All subsequent requests hang forever.
No error seem to be thrown.

I think something is wrong, but I'm still not sure where.

**Comment by yusukebe** [comment] 2024-09-12 06:38
Hi @abaudhuin !

This issue is fixed with the latest Bun. Please try it. I'll close this, but if you still have a problem, feel free to reopen it.

**Closed by yusukebe** 2024-09-12 06:38 UTC
Labels: bug
