### ISSUE TITLE
CORS no working

### ISSUE THREAD

**Issue by LRboyz** [honojs/hono#3453] opened 2024-09-26 07:26 UTC
### What version of Hono are you using?

4.6.2

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

I have two projects running locally
Front end: http://localhost:6035
Backend: http://localhost:3000
I configured cors on the backend, the following is my configuration:
**backend**
```typescript
import { cors } from "hono/cors";

const app = new Hono().basePath("/api");

// 添加 CORS 中間件
app.use(
  "/api/*",
  cors({
    origin: ["http://localhost:6035", "http://localhost"],
    allowHeaders: ["Origin", "Content-Type", "Authorization", "X-Custom-Header", "Upgrade-Insecure-Requests"], // 允許的 headers
    allowMethods: ["OPTIONS", "GET", "POST", "PATCH", "PUT", "DELETE"], // 允許的 HTTP 方法
    exposeHeaders: ["Content-Length"], // 暴露的 headers
    maxAge: 600, // 預檢請求的結果可以被快取多久（秒）
    credentials: true // 是否允許發送 cookies
  })
);

```
**client:**
```typescript
  const sendHeartbeat = useCallback(async () => {
    try {
      await ofetch(`${BASE_URL}/api/v1/heart/${userId}`, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${authToken}`, // 添加授权头
        },
        body: { message: "ping" },
      });
    } catch (error) {
      console.error("Failed to send heartbeat:", error);
    }
  }, [userId]);

  useEffect(() => {
    sendHeartbeat(); // Send initial heartbeat

    const intervalId = setInterval(sendHeartbeat, HEARTBEAT_INTERVAL);

    return () => clearInterval(intervalId); // Cleanup on component unmount
  }, [sendHeartbeat]);
```
And the backend received the options request from the frontend, but the status code was 204？：
![image](https://github.com/user-attachments/assets/a0395cd3-71a8-42ee-ac43-6a4e056596d8)
And the front end still reports an error Cors：
![image](https://github.com/user-attachments/assets/f28595d7-ee31-4dbd-bdb9-88fe2361495e)
![image](https://github.com/user-attachments/assets/75db8890-76d2-4825-be60-a29477d32910)
Did I do that step wrong? I tried all the methods mentioned in the issue but failed to solve the problem. I also tried deploying to vercel and the same thing happened. 🙏

### What is the expected behavior?

httpCode: 200

### What do you see instead?

httpCode: 204

**Comment by gavan1** [comment] 2024-09-26 23:10
Waiting for @yusukebe to add "notbug"... as this library has 0 bugs according to GitHub.

**Comment by yusukebe** [comment] 2024-09-29 07:34
Hi @LRboyz 

Maybe this is not a bug. Please provide a ***minimal*** project to reproduce it. If not, we'll close this.

**Comment by yusukebe** [comment] 2024-11-06 00:32
I'll close this since there has been no reaction for a while.

**Closed by yusukebe** 2024-11-06 00:32 UTC
Labels: triage

**Comment by bernardoforcillo** [comment] 2024-11-30 22:37
i have a similar error using hono/vercel adapter(same site), tomorrow i will create a minimal project to reproduce the error.

**Comment by EdamAme-x** [comment] 2025-01-22 08:31
Come to think of it, I recently ran into this same problem.
I debugged it a bit, but it did not work even when I created my own middleware and set up CORS.

**Comment by lizyChy0329** [comment] 2025-01-22 09:02
> Come to think of it, I recently ran into this same problem.想想看，我最近也遇到了同样的问题。 I debugged it a bit, but it did not work even when I created my own middleware and set up CORS.我调试了一下，但即使我创建了自己的中间件并设置了 CORS，它也不起作用。

When I change origin to "*", it work. But I can't send the Cookie to back-end

```js
app.use(cors({
  origin: "*",
  credentials: true,
}))
```

**Comment by yusukebe** [comment] 2025-01-22 09:07
@EdamAme-x 

Can you create a project to reproduce it?

**Comment by EdamAme-x** [comment] 2025-01-22 13:29
I cannot recall the enviroment at that time, so I am sorry to say that it is difficult to reproduce.
However, I do remember that we were using Hono on top of Next.js, so perhaps it is a Next.js issue.

If anyone else encounters the same problem, please explore if it is a Next.js issue.

**Comment by yusukebe** [comment] 2025-01-23 01:47
@EdamAme-x Okay. Thanks!

**Comment by lizyChy0329** [comment] 2025-01-23 02:50
> I cannot recall the enviroment at that time, so I am sorry to say that it is difficult to reproduce.我记不清当时的环境了，所以很遗憾地说很难重现。 However, I do remember that we were using Hono on top of Next.js, so perhaps it is a Next.js issue.不过，我确实记得我们在 Next.js 之上使用 Hono，所以这可能是 Next.js 的问题。
> 
> If anyone else encounters the same problem, please explore if it is a Next.js issue.如果其他人遇到同样的问题，请检查是否是 Next.js 问题。

I just use create-react-app to start a server:3000 for React and start hono server:3006

**Comment by yusukebe** [comment] 2025-01-23 02:52
@lizyChy0329 

Can you put the project on GitHub and share it?

**Comment by yusukebe** [comment] 2025-01-23 05:05
@lizyChy0329 Please don't use Google Drive! Put it on GitHub and share the URL.

**Comment by jjsessa** [comment] 2025-01-24 06:55
Running into this issue also... 
strict-origin-when-cross-origin
frontend on localhost:3000 backend on localhost:3001 (inside a docker container) 
cant seem to get the cors() to do anything

**Comment by guillermocalleja** [comment] 2025-03-28 13:53
I have the same issue. It was working perfectly and today when I started developing locally I run into this issue.

Runtime: nodejs v22.13.1

My frontent is an Astro app v 5.4.0:

 const response = await fetch(`${import.meta.env.PUBLIC_API_URL}/api/auth/login`, {
                method: 'POST',
                credentials: 'include',
                mode: 'cors',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data),
            })

My backend is Hono v 4.6.16:

app.use('*', cors({
    origin: ['http://localhost:4321',],
    allowHeaders: ['origin','Content-Type', 'aplication/json', 'Authorization'], 
    allowMethods: ['POST', 'GET', 'OPTIONS'],
    credentials: true,
    maxAge:600
}))

I get this error:

![Image](https://github.com/user-attachments/assets/18ea6949-3bdf-4fb3-85b7-b9fee23ec30b)

![Image](https://github.com/user-attachments/assets/2ab9064a-e6dc-484d-a57b-f2e8ef0e0ccb)

**Comment by guillermocalleja** [comment] 2025-03-28 13:56
One more detail. When I call the API from Postman Client it works perfectly.

**Comment by yusukebe** [comment] 2025-03-28 22:50
This issue was closed. If you have a problem that you think is a bug, please create a new issue and write how to reproduce it. Bye.
