### ISSUE TITLE
`deno run -A npm:create-hono@latest` doesn't exit the program

### ISSUE THREAD

**Issue by akshaybabloo** [honojs/hono#3528] opened 2024-10-18 22:24 UTC
### What version of Hono are you using?

4.6.5

### What runtime/platform is your app running on?

Deno 2.0.2

### What steps can reproduce the bug?

After running `deno run -A npm:create-hono@latest` the program never exits. Here is the output

```
$ deno run -A npm:create-hono@latest
create-hono version 0.14.1
? Target directory my-app
? Which template do you want to use? deno
✔ Cloning the template
```

The application is stuck at `Cloning the template`

### Additional information

A bug report has been submitted at Deno - https://github.com/denoland/deno/issues/26403

**Comment by yusukebe** [comment] 2024-10-18 23:35
@akshaybabloo Thank you for the PR!

Hi @blazeshomida

I think this is the same problem you want to solve with https://github.com/honojs/create-hono/pull/76. Perhaps we have to merge it to resolve this problem, though I've closed it. What do you think of it?

**Comment by blazeshomida** [comment] 2024-10-19 00:40
@yusukebe It's the same issue, although I think the issue is on the Deno side because the script only hangs with the `deno` command. It also does the same when using the `deno` command to create a Vite project.  Although not sure if it's because you need to explicitly exit the script with Deno. If so, the change I proposed should fix it. Basically just adding the exit call to the emitter `completed` callback.

**Comment by akshaybabloo** [comment] 2024-10-19 09:05
I didn't know that this issue already existed. I can comment it on Deno's side.

Would you like to keep this open as an upstream issue or close it?

**Comment by yusukebe** [comment] 2024-10-20 14:54
@blazeshomida @akshaybabloo 

This may be caused by a Deno-side bug or by it not being implemented on the Deno side. But with this PR https://github.com/honojs/create-hono/pull/76 by @blazeshomida, it will work fine. I've closed it, but now I've reopened it and will merge it. You can use the new version soon and close this issue. I think you can leave https://github.com/denoland/deno/issues/26403 open.

**Comment by yusukebe** [comment] 2024-10-23 08:51
This issue was fixed by https://github.com/honojs/create-hono/pull/76!

**Closed by yusukebe** 2024-10-23 08:51 UTC
Labels: triage
