### ISSUE TITLE
 Doesn't Check for Port Conflicts When Running Multiple Instances

### ISSUE THREAD

**Issue by Muhammad-Sarfaraz** [honojs/hono#3682] opened 2024-11-18 06:24 UTC
### What version of Hono are you using?

4.6.10

### What runtime/platform is your app running on? (with version if possible)

Cloudflare

### What steps can reproduce the bug?

Run two hono scripts, 

```
npm run dev
```

### What is the expected behavior?

When running ``` npm run dev ``` , Hono.js should check for conflicts to see if something is already running.

### What do you see instead?

But it starts as usual.

**Comment by yusukebe** [comment] 2024-11-18 06:42
Hi @Muhammad-Sarfaraz 

This is not a Hono-side issue. It's not a bug.

**Comment by EdamAme-x** [comment] 2024-11-18 07:25
I think it is the responsibility of the runtime side to detect them.  
Hono is just a framework, or a HTTP router like expressjs to be more precise, and detecting port conflicts would be adding code that is not its primary responsibility.

**Comment by Muhammad-Sarfaraz** [comment] 2024-11-19 07:00
Got it, I will mention it in the Cloudflare Wrangler Repo.

**Comment by yusukebe** [comment] 2024-11-19 07:25
Okay. Closing the issue.

**Closed by yusukebe** 2024-11-19 07:25 UTC
Labels: not bug
