### ISSUE TITLE
Type for `output` in hono client route getting dropped

### ISSUE THREAD

**Issue by shahzeb1** [honojs/hono#3020] opened 2024-06-22 00:59 UTC
### What version of Hono are you using?

^4.4.7

### What runtime/platform is your app running on?

Bun / Vite

## The Setup:

1. A `/api` folder which has a basic Hono server with some routes (uses bun)
2. A `/frontend` folder which has a react app (uses vite)

## The goal:

Use the `hono/client` in a react useQuery hook to fetch data.

## What's wrong:

Somewhere along the way, the `hc` object is not being properly typed. 

In the `/api` code, notice if I hover over the type of `ExecutionsRoute` we can see all attributes of `output`:

<img width="869" alt="Screenshot 2024-06-21 at 5 53 37 PM" src="https://github.com/honojs/hono/assets/1383831/78eabf74-ef91-46a0-b96f-a0d3d1d3ab78">

In the `/frontend` code, notice if I hover over the type of `client`, we can see the attributes of `output` getting dropped: 

<img width="896" alt="Screenshot 2024-06-21 at 5 55 01 PM" src="https://github.com/honojs/hono/assets/1383831/3a6cdf52-ce7a-486b-bc42-a3748cd9f041">

What's wild is that if I jump-to-definition of `ExecutionsRoute` from the `/frontend` folder, it correctly brings me to `/api`.

### What is the expected behavior?

The typing of the `client` which uses `hono/client` should preserve the types of the input and outputs.

### What do you see instead?

The output is getting cast to

```ts
 [x: string]: any;
```

When it should be

```ts
{
    id: string;
    prompt: string;
    jobId: string;
    done: boolean;
    result: {
        url?: string | undefined;
    } | null;
    createdAt: string;
    updatedAt: string;
}
```

### Additional information

Could it be the difference in build tools (bun vs. vite)?
I've tried restarting the TS lang server on VSCode multiple times.

**Comment by shahzeb1** [comment] 2024-06-23 20:29
I have narrowed it down, something about `createInsertSchema` from the `drizzle-zod` package, combined with `zValidator("json", test)` doesn't work well together.

Will not work:

```ts
import { createInsertSchema } from "drizzle-zod";

export const insertExecutionSchema = createInsertSchema(executionTable);

export const executionsRoute = new Hono()
  .post("/", zValidator("json", insertExecutionSchema), async (c) => {
    const execution = c.req.valid("json");
    c.status(201);
    return c.json({ hello: "world" });
  });
```

Will work:

```ts
const test = z.object({
  body: z.string(),
});

export const executionsRoute = new Hono()
  .post("/", zValidator("json", test), async (c) => {
    const execution = c.req.valid("json");
    c.status(201);
    return c.json({ hello: "world" });
  });
```

**Comment by yusukebe** [comment] 2024-06-23 20:35
@shahzeb1 

This is a TypeScript type matter, not dependent on a runtime. It does not seem to be a bug. Could you ask this on [Discussion](https://github.com/orgs/honojs/discussions) or provide a minima project to reproduce it?

**Comment by mayone-du** [comment] 2024-10-21 12:15
I have the same problem. Do you have any relevant GitHub Discussion URLs, etc.?

**Comment by yusukebe** [comment] 2024-12-23 05:21
I think we can close this issue since it's not a bug. Thanks.

**Closed by yusukebe** 2024-12-23 05:21 UTC
Labels: bug
