### ISSUE TITLE
Not sure how to connect aws sdk v3 with stream middleware

### ISSUE THREAD

**Issue by smaudd** [honojs/hono#3481] opened 2024-10-01 22:50 UTC
### Discussed in https://github.com/orgs/honojs/discussions/3480

<div type='discussions-op-text'>

<sup>Originally posted by **smaudd** October  2, 2024</sup>
Giving the next snippet:

```
try {
    const command = new GetObjectCommand(params);
    const s3Object = await s3(command); // Send the command to retrieve the object
    ctx.header("Content-Type", s3Object.ContentType);
    ctx.header("Content-Length", s3Object.ContentLength);
    ctx.header("Accept-Ranges", "bytes");

    ctx.status(206);

    return stream(
      ctx,
      async (stream) => {
        // Write a process to be executed when aborted.
        stream.onAbort(() => {
          console.log("Aborted!");
        });

        try {
          await stream.pipe(s3Object.Body.transformToWebStream());
        } catch (err) {
          // err is undefined
          console.log("Error", err);
        }
      },
      (err, stream) => {
        // Callback not triggering
      }
    );
} catch (err) {
  // Handle errors
}
 ```

 
 I'm not sure how should I pipe the ReadableStream thats coming from the GetObjectCommand execution.
 
 The ReadableStream is immediately aborting after doing the pipe and the error thats being catch is undefined. 
 
 What I am getting wrong? 
 </div>

**Comment by yusukebe** [comment] 2024-10-02 07:46
Hi @smaudd 

This is just a question, not a bug report. Please ask it in Discussions or Discord. I'm closing.

**Closed by yusukebe** 2024-10-02 07:46 UTC
