### ISSUE TITLE
Unable to add middleware after creation: Can not add a route since the matcher is already built.

### ISSUE THREAD

**Issue by JoaquimLey** [honojs/hono#3026] opened 2024-06-23 16:41 UTC
### What version of Hono are you using?

4.4.5

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

Bootstrap the app like this

```ts
app.use("*", async (c, next) => {
  const start = Date.now()
  await next()
  const end = Date.now()
  c.res.headers.set('X-Response-Time', `${end - start}`)
})

app.post("/email/confirm", (c) => {
  return c.text("Hello World");
});
```

Then during testing try to add another middleware (this is after the app is instantiated):
```ts
describe("Auth router - [POST] /email/confirm", () => {
  beforeEach(() => {
    authRouter.use("/email/confirm", async (c, next) => {
     console.log("Setting mock user in test middleware");
     const mockUser = { sub: "mock_id", email: "mock@email.com" }
     c.set("user", mockUser)
    });

    it("It should return Hello world", async () => {
      const mock_access_token = "mock_access_token";
      const res = await authRouter.request(
        "/email/confirm",
        {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${mock_access_token}` },
        },
        {}
      );

      expect(res.status).toBe(200)

      const data = await res.text();
      expect(data).toEqual("Hello World");
    });
  });
});
```

### What is the expected behavior?

I was hoping to have the "test middleware" added to this instance so I could manipulate what the user object is (I decode the JWT and set it `c.set("user", decodedUser)`

But during testing I want to have full control of what is on my context, this includes the data that was decoded from the mock jwt.

### What do you see instead?

An error is thrown:

```sh
 7 |   constructor(init) {
 8 |     Object.assign(this, init);
 9 |   }
10 |   add(method, path, handler) {
11 |     if (!this.routes) {
12 |       throw new Error(MESSAGE_MATCHER_IS_ALREADY_BUILT);
                 ^
error: Can not add a route since the matcher is already built.
      at add (***/node_modules/hono/dist/router/smart-router/router.js:12:13)
      at addRoute (***/node_modules/hono/dist/hono-base.js:160:17)
      at ***/node_modules/hono/dist/hono-base.js:69:14
      at forEach (:1:11)
      at ***/node_modules/hono/dist/hono-base.js:68:16
      at ***/src/***/***/***/router.test.ts:157:16
```

**Comment by yusukebe** [comment] 2024-06-23 20:20
Hi @JoaquimLey 

It's not a bug. As the error message, you can not add routes after handling a response. So, instantiate Hono in `beforeEach`.

**Comment by JoaquimLey** [comment] 2024-06-23 20:54
Yes I was also unsure if that was the right template for the issue.

I am, the app already exists (or else I wouldn’t be able to add the middleware, all my tests run after the hono app is created.

In a nutshell I’m looking for a way to infect things into context in my tests.

Let’s say that the bearer middleware injects the decoded user, how can I verify that the right data (eg user.id) was passed down to another layer (use case, service, repository) from the router?

**Comment by yusukebe** [comment] 2024-06-23 20:59
@JoaquimLey 

Thank you for you explanation. Understood.

@usualoma Do you have any thoughts?

**Comment by usualoma** [comment] 2024-06-23 21:29
Hi @JoaquimLey 

Is it possible to rewrite your test as follows?

```ts
describe("Auth router - [POST] /email/confirm", () => {
  let authRouter;
  beforeEach(() => {
    authRouter = new MyApp();
    authRouter.use("/email/confirm", async (c, next) => {
     console.log("Setting mock user in test middleware");
     const mockUser = { sub: "mock_id", email: "mock@email.com" }
     c.set("user", mockUser)
    });
  });

  it("It should return Hello world", async () => {
    const mock_access_token = "mock_access_token";
    const res = await authRouter.request(
      "/email/confirm",
      {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${mock_access_token}` },
      },
      {}
    );
    expect(res.status).toBe(200)
    const data = await res.text();
    expect(data).toEqual("Hello World");
  });
});
```

**Comment by usualoma** [comment] 2024-06-25 12:15
Hi @JoaquimLey
Please try the following approach.

```ts
import authRouter from "@/services/auth/auth.router";

describe("Auth router - [POST] /email/confirm", () => {
  let app;
  beforeEach(() => {
    app = new Hono();
    app.route("/email/*", authRouter);
    app.use("/email/confirm", async (c, next) => {
     console.log("Setting mock user in test middleware");
     const mockUser = { sub: "mock_id", email: "mock@email.com" }
     c.set("user", mockUser)
    });
  });

  it("It should return Hello world", async () => {
    const mock_access_token = "mock_access_token";
    const res = await app.request(
      "/email/confirm",
      {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${mock_access_token}` },
      },
      {}
    );
    expect(res.status).toBe(200)
    const data = await res.text();
    expect(data).toEqual("Hello World");
  });
});
```

**Comment by JoaquimLey** [comment] 2024-06-25 13:31
Hello @usualoma I was able to get it working! 
Thank you so much 🎉 

Your example above is also a better overall setup, that way it'll further isolate the router tests since it won't have the middleware(s) from the `root` Hono app. I had to make some small changes though:

```ts
describe("Auth router - [POST] /email/confirm", () => {
  let app: Hono;
  beforeEach(() => {
    app = new Hono();

    // IMPORTANT: Add the middleware before app.route
    // I've also, added "*" for the sake of simplicity, ofc we can set only specific routes.
    app.use("*", async (c, next) => {
      const mockUser = { sub: "mock_id", email: "mock@email.com" };
      c.set("jwt", mockUser);
      await next();
    });

    app.route("auth", authRouter);
  });

  it("It should return Hello world", async () => {
    const mock_access_token = "mock_access_token";
    const res = await app.request(
      "/auth/email/confirm",
      {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${mock_access_token}` },
      },
      MOCK_ENV
    );
    expect(res.status).toBe(200);
    const data = await res.text();
    expect(data).toEqual("Hello World");
  });
});
```

I think the most relevant part is to add the middleware before routing, it looks like it has an impact. I'm wondering if it would be possible to write a small test util to wrap/abstract all this setup, the biggest potential issue I see is requiring the "app" object to be returned and used, but maybe we could do something along the lines of a `builder` pattern for the test util, maybe expand on the `testClient ` - https://hono.dev/docs/helpers/testing

_PS: Feel free to close this issue, ty for your time and helping out!_

**Comment by JoaquimLey** [comment] 2024-06-25 13:59
Adding this WIP PR:
- https://github.com/honojs/website/pull/416/files

**Comment by yusukebe** [comment] 2024-06-27 02:02
@usualoma Thank you!

@JoaquimLey As you said, I'll close this issue now and review your PR for the website if it's ready. Thanks!

**Closed by yusukebe** 2024-06-27 02:02 UTC

**Comment by JoaquimLey** [comment] 2024-06-29 10:13
@yusukebe PR is ready for review:

- https://github.com/honojs/website/pull/416

cc @usualoma

**Comment by airtonix** [comment] 2025-08-22 10:34
I get this error when trying to use vite as the dev server for hono server side api routes.
